"""
ChatSecOps_NLQuery.py - Natural Language Query Engine (Feature 4)
=========================================================
Translates the natural language question written by the user on Slack:
  1. Converts to SQL using Gemini
  2. Executes safely in SQLite
  3. Converts the result into a readable English response using Gemini

Usage:
  from ChatSecOps_NLQuery import nl_query_engine
  result = nl_query_engine.ask("How many malicious domains are there in the last 7 days?")
"""

import sqlite3
import logging
import re
import google.generativeai as genai
import os
from datetime import datetime
from dotenv import load_dotenv

# Force load .env file at code level
load_dotenv()

logger = logging.getLogger(__name__)

# =============================================================================
# REAL DATABASE SCHEMA
# This information is given to Gemini — tables and columns must be correct.
# =============================================================================

DB_SCHEMA = """
You are the SOC Assistant of ChatSecOps. Below is the real schema of the database.

=== TABLE: domain_analysis ===
Every domain analysis is recorded in this table.
  id             INTEGER  - Auto-incrementing primary key
  domain         TEXT     - Analyzed domain name (e.g., "google.com")
  timestamp      INTEGER  - Unix timestamp (in seconds) 
  risk_score     REAL     - Risk score generated by the ML model (0.0 - 100.0)
  prediction     INTEGER  - 0 = Safe (SAFE), 1 = Malicious (MALICIOUS)
  ip_address     TEXT     - IP address of the domain
  country        TEXT     - Country of the IP
  tld            TEXT     - Top-level domain (com, net, tk, ru etc.)
  vt_malicious   INTEGER  - How many engines flagged as malicious on VirusTotal
  abuse_score    REAL     - AbuseIPDB confidence score (0-100)
  xai_summary    TEXT     - SHAP explanation summary (JSON)
  full_analysis  JSON     - All raw data
  false_positive BOOLEAN  - 0 = True threat, 1 = False positive

=== TABLE: ip_clusters ===
Domain groups sharing the same IP.
  ip_address     TEXT     - IP address (UNIQUE)
  domain_count   INTEGER  - How many domains were analyzed on this IP
  first_seen     INTEGER  - First seen Unix timestamp
  last_seen      INTEGER  - Last seen Unix timestamp
  threat_level   TEXT     - "HIGH", "MEDIUM", "LOW"

=== TABLE: domain_similarity ===
Similar domain pairs (typosquatting detection).
  domain1          TEXT  - Reference domain
  domain2          TEXT  - Similar domain
  similarity_score REAL  - Similarity between 0.0 - 1.0 (1.0 = identical)
  detected_at      INTEGER - Detection time Unix timestamp

=== TABLE: threat_campaigns ===
Campaign tracking.
  campaign_name  TEXT     - Campaign name
  indicators     TEXT     - Indicators
  domain_count   INTEGER  - Number of domains included in the campaign
  created_at     INTEGER  - Creation time
  last_activity  INTEGER  - Last activity time

=== TIME EXPRESSIONS (IMPORTANT) ===
The timestamp column is a Unix timestamp (INTEGER).
- "Last 24 hours"  → timestamp > strftime('%s','now','-1 day')
- "Last 7 days"    → timestamp > strftime('%s','now','-7 days')
- "Last 30 days"   → timestamp > strftime('%s','now','-30 days')
- "This month"     → timestamp > strftime('%s','now','start of month')

=== EXAMPLE QUERIES ===
Question: "How many domains have been analyzed?"
SQL: SELECT COUNT(*) FROM domain_analysis

Question: "Which are the top 5 most risky domains?"
SQL: SELECT domain, risk_score FROM domain_analysis ORDER BY risk_score DESC LIMIT 5

Question: "How many malicious domains were detected in the last 7 days?"
SQL: SELECT COUNT(*) FROM domain_analysis WHERE prediction = 1 AND timestamp > strftime('%s','now','-7 days')

Question: "Which countries are the threats coming from?"
SQL: SELECT country, COUNT(*) as sayi FROM domain_analysis WHERE prediction = 1 GROUP BY country ORDER BY sayi DESC LIMIT 10

Question: "Which TLD is the most malicious?"
SQL: SELECT tld, COUNT(*) as sayi FROM domain_analysis WHERE prediction = 1 GROUP BY tld ORDER BY sayi DESC LIMIT 5

Question: "The most dangerous groups sharing the same IP?"
SQL: SELECT ip_address, domain_count, threat_level FROM ip_clusters WHERE threat_level = 'HIGH' ORDER BY domain_count DESC LIMIT 5

=== ALL RULES ===
- Only generate SELECT queries. INSERT, UPDATE, DELETE, DROP are forbidden.
- Write ONLY SQL as the response — absolutely nothing else.
- Do not use Markdown (```sql), provide plain text SQL.
- Use only the tables specified above.
"""

# =============================================================================
# SAFE SQL VALIDATOR
# Gemini sometimes generates UPDATE or DROP — we prevent this.
# =============================================================================

FORBIDDEN_KEYWORDS = [
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER",
    "CREATE", "TRUNCATE", "REPLACE", "ATTACH", "DETACH"
]

def is_safe_sql(sql: str) -> bool:
    """Verifies that the generated SQL is only SELECT."""
    sql_upper = sql.upper().strip()
    
    # Must start with SELECT
    if not sql_upper.startswith("SELECT"):
        return False
    
    # Must not contain dangerous keywords
    for keyword in FORBIDDEN_KEYWORDS:
        if re.search(r'\b' + keyword + r'\b', sql_upper):
            logger.warning(f"[NLQUERY] Dangerous SQL blocked: '{keyword}' found")
            return False
    
    return True


# =============================================================================
# QUERY ENGINE
# =============================================================================

class NLQueryEngine:
    """
    Natural language → SQL → Result → Readable response
    """
    
    def __init__(self, db_path: str = "chatsecops_memory.db"):
        self.db_path = db_path
        self.gemini_model = None
        self._init_gemini()
    
    def _init_gemini(self):
        """Initialize Gemini model."""
        try:
            api_key = os.getenv("GEMINI_API_KEY")
            if not api_key:
                logger.error("[NLQUERY] GEMINI_API_KEY not found")
                return
            
            genai.configure(api_key=api_key)
            
            # FIX: The most up-to-date and working stable model is added at the top
            model_candidates = [
                "models/gemini-2.5-flash",
                "models/gemini-2.5-flash-preview-05-20",
                "models/gemini-1.5-flash-latest",
                "models/gemini-1.5-flash",
                "models/gemini-pro"
            ]
            
            for model_name in model_candidates:
                try:
                    m = genai.GenerativeModel(model_name)
                    m.generate_content("test")
                    self.gemini_model = m
                    logger.info(f"✅ [NLQUERY] Gemini ready: {model_name}")
                    break
                except Exception:
                    continue
                    
            if not self.gemini_model:
                logger.error("[NLQUERY] No Gemini model could be loaded")
                
        except Exception as e:
            logger.error(f"[NLQUERY] Gemini initialization error: {e}")
    
    def _generate_sql(self, user_question: str) -> str:
        """
        Give the schema + question to Gemini, generate SQL.
        Returns: SQL string or None in case of an error
        """
        if not self.gemini_model:
            return None
        
        prompt = f"""{DB_SCHEMA}

User Question: "{user_question}"
SQL Query:"""
        
        try:
            response = self.gemini_model.generate_content(prompt)
            sql = response.text.strip()
            
            # Clear Markdown
            sql = sql.replace("```sql", "").replace("```", "").strip()
            
            # Remove semicolon
            sql = sql.rstrip(";").strip()
            
            logger.info(f"[NLQUERY] Generated SQL: {sql}")
            return sql
            
        except Exception as e:
            logger.error(f"[NLQUERY] SQL generation error: {e}")
            return None
    
    def _execute_sql(self, sql: str) -> tuple:
        """
        Safely execute SQL in SQLite.
        """
        if not is_safe_sql(sql):
            return None, "Security check: This type of query is not allowed."
        
        try:
            conn = sqlite3.connect(self.db_path)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            cursor.execute(sql)
            rows = cursor.fetchall()
            
            column_names = [desc[0] for desc in cursor.description] if cursor.description else []
            conn.close()
            
            rows_as_dicts = [dict(row) for row in rows]
            logger.info(f"[NLQUERY] Query successful: {len(rows_as_dicts)} rows returned")
            return rows_as_dicts, column_names
            
        except sqlite3.OperationalError as e:
            logger.error(f"[NLQUERY] SQL execution error: {e}")
            return None, f"Database error: {str(e)}"
        except Exception as e:
            logger.error(f"[NLQUERY] Unexpected error: {e}")
            return None, str(e)
    
    def _format_response(self, user_question: str, rows: list, columns: list) -> str:
        """
        Convert raw database result into a readable response using Gemini.
        """
        if not self.gemini_model:
            if not rows:
                return "📭 No records found in the database for this query."
            return f"📊 Query result ({len(rows)} records):\n" + "\n".join(str(r) for r in rows[:10])
        
        if not rows:
            return "📭 No records found in the database for this query."
        
        display_rows = rows[:20]
        truncated = len(rows) > 20
        
        prompt = f"""You are the SOC Assistant for ChatSecOps. Respond to the user by interpreting the database query results.

User's Question: "{user_question}"

Raw Data from Database:
Columns: {columns}
Rows: {display_rows}
{"(Note: First 20 rows are shown, total " + str(len(rows)) + " records)" if truncated else ""}

Please write your response according to these rules:
- Write in English
- Use a professional yet understandable SOC analyst tone
- Highlight numerical data
- Emphasize important findings if any (e.g., many malicious domains, risky IPs)
- 2-4 sentences are enough
- You can use emojis (📊 🔴 ⚠️ ✅)
- Write only the response, do not add anything else
"""
        
        try:
            response = self.gemini_model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            logger.error(f"[NLQUERY] Response formatting error: {e}")
            lines = [f"📊 *Query Result* ({len(rows)} records):"]
            for row in display_rows[:10]:
                lines.append("• " + " | ".join(f"{k}: {v}" for k, v in row.items()))
            return "\n".join(lines)
    
    def ask(self, user_question: str) -> dict:
        """
        Main entry point. Takes a question, returns a response.
        """
        logger.info(f"[NLQUERY] Question: {user_question}")
        
        if not self.gemini_model:
            return {
                "answer": "❌ AI model is currently not active. Please contact the system administrator.",
                "sql": None,
                "row_count": 0,
                "success": False
            }
        
        sql = self._generate_sql(user_question)
        if not sql:
            return {
                "answer": "❌ Your question could not be converted to an SQL query. Try asking a clearer question.",
                "sql": None,
                "row_count": 0,
                "success": False
            }
        
        rows, columns_or_error = self._execute_sql(sql)
        
        if rows is None:
            logger.error(f"[NLQUERY] SQL failed: {columns_or_error}")
            try:
                fallback_prompt = f"""You are the ChatSecOps SOC Assistant. 
The user asked: "{user_question}"
A technical error occurred while running the database query.
Write a short, polite, English error message to the user. Do not provide SQL details."""
                fallback = self.gemini_model.generate_content(fallback_prompt).text.strip()
                return {
                    "answer": fallback,
                    "sql": sql,
                    "row_count": 0,
                    "success": False
                }
            except:
                return {
                    "answer": f"⚠️ An error occurred while executing the query. Try a different question.",
                    "sql": sql,
                    "row_count": 0,
                    "success": False
                }
        
        formatted_answer = self._format_response(user_question, rows, columns_or_error)
        
        return {
            "answer": formatted_answer,
            "sql": sql,
            "row_count": len(rows),
            "success": True
        }

# =============================================================================
# SINGLETON
# =============================================================================
nl_query_engine = NLQueryEngine()