"""
ChatSecOps_Analytics.py - ENGLISH VERSION
All Turkish text replaced with English for international publication
"""
import os
import matplotlib.pyplot as plt
from fpdf import FPDF
from datetime import datetime
import re

plt.switch_backend('Agg')

THEME = {
    'header_bg': (255, 255, 255),
    'text_primary': (33, 37, 41),
    'text_secondary': (108, 117, 125),
    'accent_line': (222, 226, 230),
    'box_bg': (248, 249, 250)
}

def clean_text(text):
    """FPDF character cleanup"""
    if not isinstance(text, str): return str(text)
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    # Turkish character mapping (for backwards compatibility)
    tr_map = {'ğ':'g', 'Ğ':'G', 'ş':'s', 'Ş':'S', 'ı':'i', 'İ':'I', 'ö':'o', 'Ö':'O', 'ü':'u', 'Ü':'U', 'ç':'c', 'Ç':'C'}
    for tr, en in tr_map.items(): text = text.replace(tr, en)
    return text

class ProfessionalReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 20)
        self.set_text_color(*THEME['text_primary'])
        self.cell(0, 10, 'SECURITY ASSESSMENT', 0, 1, 'L')
        
        self.set_font('Arial', '', 10)
        self.set_text_color(*THEME['text_secondary'])
        self.cell(0, 5, 'ChatSecOps Automated Intelligence Report', 0, 1, 'L')
        
        self.set_draw_color(*THEME['accent_line'])
        self.set_line_width(0.5)
        self.line(10, 28, 200, 28)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(*THEME['text_secondary'])
        self.cell(0, 10, f'Confidential | Generated by ChatSecOps | Page {self.page_no()}', 0, 0, 'C')

    def section_title(self, title):
        self.ln(5)
        self.set_font('Arial', 'B', 12)
        self.set_text_color(*THEME['text_primary'])
        self.set_fill_color(*THEME['box_bg'])
        self.cell(0, 8, f"  {title.upper()}", 0, 1, 'L', True)
        self.ln(2)

def generate_minimal_charts(risk_score):
    """Generate risk bar chart"""
    if not os.path.exists("static/charts"): os.makedirs("static/charts", exist_ok=True)
    
    plt.figure(figsize=(8, 1.5))
    
    # Background bar (Gray)
    plt.barh([0], [100], color='#e9ecef', height=0.5)
    
    # Risk bar (color by severity)
    color = '#dc3545' if risk_score > 75 else '#ffc107' if risk_score > 40 else '#28a745'
    plt.barh([0], [risk_score], color=color, height=0.5)
    
    plt.xlim(0, 100)
    plt.axis('off')
    
    # Score text
    plt.text(risk_score + 1, 0, f"{risk_score:.1f}%", va='center', fontsize=12, fontweight='bold', color='#495057')
    
    filename = "static/charts/risk_bar_modern.png"
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.close()
    return filename

def create_pdf_report(domain, ai_summary, risk_score, vt_stats, abuse_data=None, osint_data=None, shap_path=None):
    pdf = ProfessionalReport()
    pdf.add_page()
    
    # 1. INFO BOX
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(*THEME['text_primary'])
    pdf.cell(40, 6, "Target Asset:", 0, 0)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 6, clean_text(domain), 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(40, 6, "Analysis Date:", 0, 0)
    pdf.cell(0, 6, datetime.now().strftime('%Y-%m-%d %H:%M UTC'), 0, 1)
    
    # 2. RISK SCORE
    pdf.ln(5)
    chart_path = generate_minimal_charts(risk_score)
    pdf.image(chart_path, x=10, y=pdf.get_y(), w=140)
    pdf.ln(25)
    
    # Verdict
    verdict = "CRITICAL" if risk_score > 80 else "HIGH" if risk_score > 60 else "MEDIUM" if risk_score > 30 else "SAFE"
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, f"VERDICT: {verdict} RISK", 0, 1)

    # 3. INTELLIGENCE TABLE
    pdf.section_title("Threat Intelligence Fusion")
    
    # Headers
    pdf.set_font('Arial', 'B', 9)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(50, 8, "Source", 1, 0, 'L', True)
    pdf.cell(100, 8, "Finding", 1, 0, 'L', True)
    pdf.cell(40, 8, "Status", 1, 1, 'C', True)
    
    # Data rows
    pdf.set_font('Arial', '', 9)
    
    def add_row(source, finding, status):
        pdf.cell(50, 8, clean_text(source), 1)
        pdf.cell(100, 8, clean_text(finding), 1)
        pdf.set_font('Arial', 'B', 9)
        pdf.cell(40, 8, clean_text(status), 1, 1, 'C')
        pdf.set_font('Arial', '', 9)

    # ML Model
    add_row("ChatSecOps AI", f"Behavioral Risk Score: {risk_score:.1f}%", verdict)
    
    # VirusTotal
    vt_mal = vt_stats.get('malicious', 0) if vt_stats else 0
    add_row("VirusTotal", f"{vt_mal} security vendors flagged", "MALICIOUS" if vt_mal > 0 else "CLEAN")
    
    # AbuseIPDB
    if abuse_data and "hata" not in abuse_data and "error" not in abuse_data:
        add_row("AbuseIPDB", f"Confidence: {abuse_data.get('abuseConfidenceScore', 0)}%", "HIGH" if abuse_data.get('abuseConfidenceScore', 0) > 50 else "LOW")
    else:
        add_row("AbuseIPDB", "No IP Address Resolved", "SKIPPED")

    # AlienVault
    if osint_data:
        av = osint_data.get('alienvault', {})
        if av and not av.get('error'):
            pulses = av.get('pulse_count', 0)
            add_row("AlienVault OTX", f"{pulses} Threat Pulses found", "FOUND" if pulses > 0 else "CLEAN")
        else:
            add_row("AlienVault OTX", "No data / Error", "N/A")
        
        # Shodan
        sho = osint_data.get('shodan')
        if sho:
            if sho.get('error'):
                add_row("Shodan", "IP Address not found/resolved", "SKIPPED")
            else:
                ports = sho.get('ports', [])
                add_row("Shodan", f"Open Ports: {len(ports)} ({str(ports)[:20]}...)", "INFO")
                if sho.get('vulns'):
                    add_row("Shodan Vulns", f"{len(sho['vulns'])} CVEs Detected", "VULNERABLE")
        else:
             add_row("Shodan", "No data available", "N/A")

    # 4. AI ANALYSIS
    pdf.ln(5)
    pdf.section_title("AI Analysis & Reasoning")
    pdf.set_font('Arial', '', 9)
    
    # Clean text
    explanation = clean_text(str(ai_summary))
    explanation = explanation.replace('*', '').replace('#', '') 
    pdf.multi_cell(0, 5, explanation)
    
    # 5. TECHNICAL FORENSICS (XAI Graph)
    if shap_path and os.path.exists(shap_path):
        pdf.add_page()
        pdf.section_title("Technical Forensics (XAI Analysis)")
        pdf.ln(5)
        pdf.write(5, "This chart visualizes the specific features that influenced the AI's decision.")
        pdf.ln(10)
        try:
            pdf.image(shap_path, x=10, y=pdf.get_y(), w=190)
        except:
            pdf.write(5, "[Error rendering Graph]")

    # Save file
    if not os.path.exists("static/reports"): os.makedirs("static/reports", exist_ok=True)
    filename = f"static/reports/Report_{clean_text(domain)}.pdf"
    try:
        pdf.output(filename)
        return filename
    except Exception as e:
        print(f"PDF Error: {e}")
        return ""